### ISSUE TITLE
Plugin "Protected Albums" does not work properly

### ISSUE THREAD

**Issue by coyotede** [Piwigo/piwigo-bootstrap-darkroom#213]
Hello,

I tried using "bootstrap-darkroom" with "protected albums". 
On a click on an albums icon the album password is requested (ok)... but if you click (not logged in) onto "calender" and select the date which the protected pictures has been uploaded (maybe also work with 'random image') you can view the pictures in full size without entering the album password! (not ok)

With other themes (like "stripped_responsive") this works properly - you have also to enter the album password to view those protected pictures.

Rgds
Dieter

**Comment by plegall** [comment]
Plugin "Protected Album" is no longer maintained. Let's close this issue.
