### ISSUE TITLE
Reduce Height of Hero Header

### ISSUE THREAD

**Issue by sjgarth** [Piwigo/piwigo-bootstrap-darkroom#322]
Hi,
I cannot find the code for the hero header, and i wish to reduce its height by about half.
Any idea how to do this?
Thanks

**Comment by HWFord** [comment]
You can acheive this with css, using the LocalFilesEditor plugin. 

Here is an example of how to reduce the height of the hero header by half
```
.page-header.page-header-small {
    height: 30vh;
}
```
