### ISSUE TITLE
    Bootstrap Darkroom - No Titles and Descriptions in PhotoSwipe Diashow

### ISSUE THREAD

**Issue by ClaudiaLev** [Piwigo/piwigo-bootstrap-darkroom#327]
I use the Bootstrap Darkroom with PhotoSwipe Diashow

When I look at an separate photo with PhotoSwipe, there is just the photo and at the bottom of the site it shows the filename.
I think this behavior has changed and I think that the title and the description of the photo was visible in earlier versions of bootstrap darkroom.

It would be nice to fix this, that the title and the description of the photo is shown when using PhotoSwipe Diashow.

**Comment by RStoroy** [comment]
You can try to replace the file:
themes/bootstrap_darkroom/template/_photoswipe_js.tpl
With my customized:  https://www.arkivfoto.net/_photoswipe_js.txt
Rename to .tpl

**Comment by ClaudiaLev** [comment]
Thanks RStoroy!
It works by changing the themecontroller.php, you mentioned in the Piwigo Forum.

@plegall 

Please can this change be implented in the upcoming version of Bootstrap Darkroom in **themecontroller.ph**p.
I think this helpful for every user.

![Textvergleich  60tools - Mozilla Firefox 24 07 2022 232459 bmp](https://user-images.githubusercontent.com/30748040/180666624-0f5add51-168f-469a-b6b8-75d53934c8ba.jpg)

![Afrika  SüdafrikaSwasiland  www die-weite-welt de - Fotografien von Claudia Leverentz - Mozilla Firefox 24 07 2022 231130 bmp](https://user-images.githubusercontent.com/30748040/180666824-fdf1ed0a-4a75-4abe-9dc4-35877f3da1b6.jpg)
