### ISSUE TITLE
Image description missing in photoswipe mode

### ISSUE THREAD

**Issue by aberwenig** [Piwigo/piwigo-bootstrap-darkroom#338]
I have a Piwigo 12.3.0 system with Bootstrap-Darkroom 2.5.10.

When viewing images with Photoswipe, the image description, which should appear below, is missing.

I tried to find why. In file '.../themes/bootstrap_darkroom/template/_photoswipe_js.tpl', line 56:

                     if ($(this).data('description').length > 0) {$title += '<ul id="pswp--caption--description"><li>' + $(this).data('description') + '</li></ul>'; }

$(this).data('description') is always empty. Somehow it does not get read correctly from the image properties. I couldn't find where that happens.

For comparison: I have another Piwigo system version 2.10.2 with Bootstrap-Darkroom 2.4.5 and there it works fine.

**Comment by ClaudiaLev** [comment]
I had the same problem:
https://github.com/Piwigo/piwigo-bootstrap-darkroom/issues/327

It will be fixed with the next update.

**Comment by aberwenig** [comment]
Hey, ClaudiaLev,

I had a look at issue #327 you mentioned. I tried the solution described there (modify the file 'themecontroller.php') and now it works.

Thanks a lot!

**Comment by aberwenig** [comment]
Merge with issue #327
